# Configuration file for MegaLinter

# all, none, or list of linter keys (assumming this runs locally and not on CI)
APPLY_FIXES: all

CLEAR_REPORT_FOLDER: true

DEFAULT_BRANCH: main

VALIDATE_ALL_CODEBASE: false

ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - BASH_SHELLCHECK
  - REPOSITORY_GIT_DIFF
  - PYTHON_BLACK
  - JSON_ESLINT_PLUGIN_JSONC
  - C_CLANG_FORMAT
  - MAKEFILE_CHECKMAKE
  - JAVASCRIPT_PRETTIER
  - CSHARP_ROSLYNATOR
  - GO_GOLANGCI_LINT
  - MAKEFILE_CHECKMAKE
  - POWERSHELL_POWERSHELL
  - SQL_SQLFLUFF
  - PROTOBUF_PROTOLINT
  - YAML_PRETTIER
  - DOCKERFILE_HADOLINT
  - SPELL_PROSELINT

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

LINTER_RULES_PATH: .github/linters

C_CLANG_FORMAT_CONFIG_FILE: .clang-format

LOG_LEVEL: INFO

PARALLEL_PROCESS_NUMBER: 20
