# Configuration file for MegaLinter

APPLY_FIXES: none

CLEAR_REPORT_FOLDER: true

DEFAULT_BRANCH: main

VALIDATE_ALL_CODEBASE: false

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

LINTER_RULES_PATH: .github/linters

C_CLANG_FORMAT_CONFIG_FILE: .clang-format

LOG_LEVEL: INFO

PARALLEL_PROCESS_NUMBER: 20
