name: Commitlint CI

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6