name: PR Watcher

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if (context.payload.pull_request.additions > MAX_PR_SIZE) {
              github.rest.issues.createComment({
              issue_number: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: PR size is too large. Please keep PR size under ${MAX_PR_SIZE} additions.`
              });
              core.setFailed(`PR size is too large. Please keep PR size under ${MAX_PR_SIZE} additions.`);
            } else { core.notice(`PR size is within limits.`); }