name: PR Watcher

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          MAX_PR_SIZE: 500
          GLOB: "['**/*.md', '**/*.yaml', '**/*.yml', '**/*.json']"
        with:
          script: |
            const MAX_PR_SIZE = parseInt(process.env.MAX_PR_SIZE);
            const pr = context.payload.pull_request;

            const changedFiles = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });

            const filesAfterGlob = glob(process.env.GLOB, { sync: true });
            core.notice(`Files after glob: ${filesAfterGlob}`);

            const totalAdditions = changedFiles.data.reduce((acc, file) => {
              if (filesAfterGlob.includes(file.filename)) 
                return acc + file.additions;
              return 0;
              }
              return acc + file.additions;
            }, 0);


            if (totalAdditions > MAX_PR_SIZE) {
              github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: PR size is too large. Please keep PR size under ${MAX_PR_SIZE} additions.`
              });
              core.setFailed(`PR size is too large. Please keep PR size under ${MAX_PR_SIZE} additions.`);
            } else { core.notice(`PR size is within limits.`); }