name: Set Repo Default Settings

on:
    workflow_dispatch:

permissions: write-all

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
                DEFAULT_REPO_NAME: 'monorepo'
                DEFAULT_REPO_DESCRIPTION: 'A monorepo for all the things'
                DEFAULT_REPO_HOMEPAGE: ''
                DEFAULT_REPO_PRIVATE: false
                DEFAULT_REPO_VISIBILITY: 'public'
                DEFAULT_SECURITY_AND_ANALYSIS_ADV_SEC_STATUS: 'enabled'
                DEFAULT_SECURITY_AND_ANALYSIS_SECRET_SCANNING: 'enabled'
                DEFAULT_SECURITY_AND_ANALYSIS_SECRET_SCANNING_PUSH_PROTECTION: 'enabled'
                DEFAULT_HAS_ISSUES: true
                DEFAULT_HAS_PROJECTS: true
                DEFAULT_HAS_WIKI: true
                DEFAULT_IS_TEMPLATE: true
                DEFAULT_BRANCH: 'main'
                DEFAULT_ALLOW_SQUASH_MERGE: true
                DEFAULT_ALLOW_MERGE_COMMIT: false
                DEFAULT_ALLOW_REBASE_MERGE: false
                DEFAULT_ALLOW_AUTO_MERGE: false
                DEFAULT_DELETE_BRANCH_ON_MERGE: true
                DEFAULT_ALLOW_UPDATE_BRANCH: true
                DEFAULT_SQUASH_MERGE_COMMIT_TITLE: 'COMMIT_OR_PR_TITLE'
                DEFAULT_SQUASH_MERGE_COMMIT_MESSAGE: 'PR_BODY'
                DEFAULT_MERGE_COMMIT_TITLE: 'PR_TITLE'
                DEFAULT_MERGE_COMMIT_MESSAGE: 'PR_BODY'
                DEFAULT_ARCHIVED: false
                DEFAULT_ALLOW_FORKING: true
                DEFAULT_WEB_COMMIT_SIGNOFF_REQUIRED: true
        with:
          script: |
            github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
                name: process.env.DEFAULT_REPO_NAME,
                description: process.env.DEFAULT_REPO_DESCRIPTION,
                homepage: process.env.DEFAULT_REPO_HOMEPAGE,
                private: process.env.DEFAULT_REPO_PRIVATE,
                visibility: process.env.DEFAULT_REPO_VISIBILITY,
                security_and_analysis: {
                    advanced_security: {
                     status: process.env.DEFAULT_SECURITY_AND_ANALYSIS_ADV_SEC_STATUS
                    },
                    secret_scanning: {
                        status: process.env.DEFAULT_SECURITY_AND_ANALYSIS_SECRET_SCANNING,
                     },
                    secret_scanning_push_protection:{
                        status: process.env.DEFAULT_SECURITY_AND_ANALYSIS_SECRET_SCANNING_PUSH_PROTECTION
                    }
                },
                has_issues: process.env.DEFAULT_HAS_ISSUES,
                has_projects: process.env.DEFAULT_HAS_PROJECTS,
                has_wiki: process.env.DEFAULT_HAS_WIKI,
                is_template: process.env.DEFAULT_IS_TEMPLATE,
                default_branch: process.env.DEFAULT_BRANCH,
                allow_squash_merge: process.env.DEFAULT_ALLOW_SQUASH_MERGE,
                allow_merge_commit: process.env.DEFAULT_ALLOW_MERGE_COMMIT,
                allow_rebase_merge: process.env.DEFAULT_ALLOW_REBASE_MERGE,
                allow_auto_merge: process.env.DEFAULT_ALLOW_AUTO_MERGE,
                delete_branch_on_merge: process.env.DEFAULT_DELETE_BRANCH_ON_MERGE,
                allow_update_branch: process.env.DEFAULT_ALLOW_UPDATE_BRANCH,
                squash_merge_commit_title: process.env.DEFAULT_SQUASH_MERGE_COMMIT_TITLE,
                squash_merge_commit_message: process.env.DEFAULT_SQUASH_MERGE_COMMIT_MESSAGE,
                merge_commit_title: process.env.DEFAULT_MERGE_COMMIT_TITLE,
                merge_commit_message: process.env.DEFAULT_MERGE_COMMIT_MESSAGE,
                archived: process.env.DEFAULT_ARCHIVED,
                allow_forking: process.env.DEFAULT_ALLOW_FORKING,
                web_commit_signoff_required: process.env.DEFAULT_WEB_COMMIT_SIGNOFF_REQUIRED
            });
        


